export const officerInfo = {
  president: {
    name: "Brady Dodd",
    position: "President",
    email: "bcdkcd@mst.edu",
    img: "/images/about/officers/1.jpg",
  },
  vicePresident: {
    name: "Will Becker",
    position: "Vice President",
    email: "webmk7@mst.edu",
    img: "/images/about/officers/2.jpg",
  },
  recordingSecretary: {
    name: "Joshua Gilbert",
    position: "Recording Secretary",
    email: "jtgbnr@mst.edu",
    img: "/images/about/officers/3.jpg",
  },
  correspondingSecretary: {
    name: "Noah Bauman",
    position: "Corresponding Secretary",
    email: "nb887@mst.edu",
    img: "/images/about/officers/4.jpg",
  },
  historian: {
    name: "Zane Bergmann",
    position: "Historian",
    email: "znbgm8@umsystem.edu",
    img: "/images/about/officers/5.jpg",
  },
  purser: {
    name: "Colin Drago",
    position: "Purser (Treasurer)",
    email: "cbdmmb@umsystem.edu",
    img: "/images/about/officers/6.jpg",
  },
  parliamentarian: {
    name: "Carter Shewmaker",
    position: "Parliamentarian",
    email: "csd9m@mst.edu",
    img: "/images/about/officers/7.jpg",
  },
  sergeantAtArms: {
    name: "Derek Smith",
    position: "Sergeant-at-Arms",
    email: "drs5xb@mst.edu",
    img: "/images/about/officers/8.jpg",
  },
  marshal: {
    name: "Joey Mach",
    position: "Marshal",
    email: "jdm5th@mst.edu",
    img: "/images/about/officers/9.jpg",
  },
  recuitmentChairman1: {
    name: "Luke Gerling",
    position: "Recruitment Chairman",
    email: "lgqkb@umsystem.edu",
    img: "/images/about/officers/rc1.jpg",
  },
  recuitmentChairman2: {
    name: "Joshua Fallert",
    position: "Recruitment Chairman",
    email: "jfxnh@umsystem.edu",
    img: "/images/about/officers/rc2.jpg",
  },
  houseManager1: {
    name: "Patrick Schilly",
    position: "House Manager",
    email: "ps4rr@umsystem.edu",
    img: "/images/about/officers/hm1.jpg",
  },
  houseManager2: {
    name: "Myles Harms",
    position: "House Manager",
    email: "mh4fh@umsystem.edu",
    img: "/images/about/officers/hm2.jpg",
  },
  steward: {
    name: "Colin Henderson",
    position: "Steward",
    email: "chqp2@umsystem.edu",
    img: "/images/about/officers/steward.jpg",
  },
};
