export const officerInfo = {
  president: {
    name: "Marco Miskovic",
    position: "President",
    email: "msmgg5@umsystem.edu",
    img: "/images/about/officers/1.jpg",
  },
  vicePresident: {
    name: "Christopher Altamirano",
    position: "Vice President",
    email: "ceak3z@umsystem.edu",
    img: "/images/about/officers/2.jpg",
  },
  recordingSecretary: {
    name: "Ian Vacek",
    position: "Recording Secretary",
    email: "ijvkmc@umsystem.edu",
    img: "/images/about/officers/3.jpg",
  },
  correspondingSecretary: {
    name: "Brady Dodd",
    position: "Corresponding Secretary",
    email: "bcdkcd@umsystem.edu",
    img: "/images/about/officers/4.jpg",
  },
  historian: {
    name: "Gabriel Frederick",
    position: "Historian",
    email: "gf5xp@umsystem.edu",
    img: "/images/about/officers/5.jpg",
  },
  purser: {
    name: "Jacob Peterson",
    position: "Purser (Treasurer)",
    email: "jlpxwt@umsystem.edu",
    img: "/images/about/officers/6.jpg",
  },
  parliamentarian: {
    name: "William Becker",
    position: "Parliamentarian",
    email: "webmk7@umsystem.edu",
    img: "/images/about/officers/7.jpg",
  },
  sergeantAtArms: {
    name: "Samuel Kantarevic",
    position: "Sergeant-at-Arms",
    email: "samuelkantarevic@mst.edu",
    img: "/images/about/officers/8.jpg",
  },
  marshal: {
    name: "Jacob Lewis",
    position: "Marshal",
    email: "jmlpx7@umsystem.edu",
    img: "/images/about/officers/9.jpg",
  },
  recuitmentChairman1: {
    name: "Noah Bauman",
    position: "Recruitment Chairman",
    email: "nb887@umsystem.edu",
    img: "/images/about/officers/rc1.jpg",
  },
  recuitmentChairman2: {
    name: "Bailey Hermann",
    position: "Recruitment Chairman",
    email: "bahrqc@umsystem.edu",
    img: "/images/about/officers/rc2.jpg",
  },
  houseManager1: {
    name: "Grant Jones",
    position: "House Manager",
    email: "gajgdd@umsystem.edu",
    img: "/images/about/officers/hm1.jpg",
  },
  houseManager2: {
    name: "Preston Lurk",
    position: "House Manager",
    email: "pjlm7d@umsystem.edu",
    img: "/images/about/officers/hm2.jpg",
  },
  steward: {
    name: "Carter Shewmaker",
    position: "Steward",
    email: "csd9m@umsystem.edu",
    img: "/images/about/officers/steward.jpg",
  },
};
