export const officerInfo = {
  president: {
    name: "Trey Brown",
    position: "President",
    email: "twbyny@umsystem.edu",
    pledgeClass: "2021",
    img: "/images/about/officers/1.jpg",
  },
  vicePresident: {
    name: "Matthew Sherman",
    position: "Vice President",
    email: "mrsdmw@umsystem.edu",
    pledgeClass: "2021",
    img: "/images/about/officers/2.jpg",
  },
  recordingSecretary: {
    name: "Ian Vacek",
    position: "Recording Secretary",
    email: "ijvkmc@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/3.jpg",
  },
  correspondingSecretary: {
    name: "Chris Altamirano",
    position: "Corresponding Secretary",
    email: "ceak3z@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/4.jpg",
  },
  historian: {
    name: "Sam Wright",
    position: "Historian",
    email: "sjwf3b@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/5.jpg",
  },
  purser: {
    name: "Alex Huebner",
    position: "Purser (Treasurer)",
    email: "achgzg@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/6.jpg",
  },
  parliamentarian: {
    name: "Marco Miskovic",
    position: "Parliamentarian",
    email: "msmgg5@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/7.jpg",
  },
  sergeantAtArms: {
    name: "Josh Burrows",
    position: "Sergeant-at-Arms",
    email: "jbbz3c@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/8.jpg",
  },
  marshal: {
    name: "Brayden Martin",
    position: "Marshal",
    email: "bjmtgd@umsystem.edu",
    pledgeClass: "2022",
    img: "/images/about/officers/9.jpg",
  },
  recuitmentChairman1: {
    name: "Brady Dodd",
    position: "Recruitment Chairman",
    email: "bcdkcd@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/rc1.jpg",
  },
  recuitmentChairman2: {
    name: "Parker Bruns",
    position: "Recruitment Chairman",
    email: "pjb4kh@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/rc2.jpg",
  },
  houseManager1: {
    name: "Zach Feise",
    position: "House Manager",
    email: "zcfgv6@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/hm1.jpg",
  },
  houseManager2: {
    name: "Jake Peterson",
    position: "House Manager",
    email: "jlpxwt@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/hm2.jpg",
  },
  steward: {
    name: "Braden Bergmann",
    position: "Steward",
    email: "bsbhtn@umsystem.edu",
    pledgeClass: "2023",
    img: "/images/about/officers/steward.jpg",
  },
};
