import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";

import theme from "../utils/theme.js";
import Layout from "../components/Layout/Layout.js";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>React/Next.js Refactor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Layout />
        <Component {...pageProps} />
      </ThemeProvider>
    </div>
  );
}

export default MyApp;
